### ISSUE TITLE
Брать язык из базы bitzlato

### ISSUE THREAD

**Issue by dapi** [bitzlato/mailer#3]

**Comment by huryv45** [comment]
@dapi речь о `user_profile.lang_web` ?

**Comment by dapi** [comment]
А что если дать тебе открытое API по которому можешь по email-e узнавать язык? Чтобы не лазить в базу? Почтовая рассылка не такая частая, можно делать запросы. А еще можно кешировать язык для пользователя на 5 минут.

**Comment by huryv45** [comment]
Легко, давай сделаем следующим этапом
